citizen_report/citizen_report/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authSystem/', include('authSystem.urls')),
    path('', include('report.urls')),
    path('', include('news.urls')),
]

citizen_report/news/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path, include

from . import views

urlpatterns = [
    path('reports/<int:pk>/news/', views.NewsPostList.as_view(), name='news'),
    path('reports/<int:pk>/create-news/', staff_member_required(views.NewsPostCreate.as_view()), name='create_news'),
    path('news/<int:pk>/', views.NewsPostDetail.as_view(), name='detail_news'),
    path('news/<int:pk>/comment/', views.NewsCommentCreate.as_view(), name='add_comment_to_news'),
]

citizen_report/report/urls.py
from django.urls import path
from . import views
from .views import ReportListView, MyReportListView, ReportCreate

urlpatterns = [
    path('', views.home, name='home'),
    path('reports/', ReportListView.as_view(), name='reports'),
    path('my-reports/', MyReportListView.as_view(), name='my_reports'),
    path('create/', ReportCreate.as_view(), name='create'),
    path('reports/<int:report_id>/', views.detail, name='detail'),
    path('update-report/<int:report_id>/', views.update_status, name='update_report'),
]

citizen_report/report/models.py
from django.conf import settings
from django.db import models

from .constants import Category, Status

User = settings.AUTH_USER_MODEL


class Report(models.Model):
    title = models.CharField(max_length=120)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='images/', blank=True)
    category = models.CharField(max_length=3, choices=Category.choices)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.PENDING)
    user = models.ForeignKey(User, related_name='reports', on_delete=models.CASCADE)
    clerk = models.ForeignKey(User, related_name='assigned_reports', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-updated_at']

    def __str__(self):
        return f'{self.title} | {self.updated_at}'

citizen_report/report/forms.py
from django import forms

from .models import Report


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('title', 'text', 'image', 'category')


class UpdateReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('status',)

citizen_report/report/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, Count
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from django_filters.views import FilterView

from .filter import ReportFilter, MyReportFilter
from .forms import ReportForm, UpdateReportForm
from .models import Report
from .utils import assign_clerk
from news.models import NewsPost

User = get_user_model()


def home(request):
    reports = Report.objects.order_by('-created_at')
    news_list = NewsPost.objects.order_by('-created_at')

    return render(request, 'home.html', {'reports': reports, 'news_list': news_list})


class ReportListView(FilterView):
    model = Report
    template_name = 'reports.html'
    context_object_name = 'reports'
    paginate_by = 4
    filterset_class = ReportFilter

    def get_queryset(self, *args, **kwargs):
        search = self.request.GET.get('search')
        queryset = super().get_queryset(**kwargs)
        if search:
            queryset = queryset.filter(
                Q(title__icontains=search) |
                Q(text__icontains=search) |
                Q(category__icontains=search)
            )
        return queryset


class MyReportListView(LoginRequiredMixin, FilterView):
    login_url = 'login'
    model = Report
    template_name = 'my_reports.html'
    context_object_name = 'reports'
    paginate_by = 2
    filterset_class = MyReportFilter

    def get_queryset(self, *args, **kwargs):
        user = self.request.user
        queryset = super().get_queryset(**kwargs)
        if user.is_staff:
            queryset = queryset.filter(
                clerk=user
            )
        else:
            queryset = queryset.filter(
                user=user
            )
        return queryset


class ReportCreate(LoginRequiredMixin, generic.CreateView):
    login_url = 'login'
    form_class = ReportForm
    success_url = reverse_lazy("reports")
    template_name = "create.html"

    def get_form_kwargs(self):
        kwargs = super(ReportCreate, self).get_form_kwargs()
        if hasattr(self.request, 'clerk'):
            kwargs['clerk'] = self.request.clerk
        return kwargs

    def form_valid(self, form):
        if self.kwargs.get('clerk'):
            form.instance.clerk = self.kwargs.get('clerk')
        else:
            assign_clerk(form.instance)
        form.instance.user = self.request.user
        return super(ReportCreate, self).form_valid(form)


def detail(request, report_id):
    report = get_object_or_404(Report, id=report_id)
    posts = report.report_posts.all()
    return render(request, 'detail.html', {'report': report, 'posts': posts})


@login_required(login_url='login')
def update_status(request, report_id):
    if request.user.is_staff:
        report = get_object_or_404(Report, id=report_id, clerk=request.user)
        if request.method == 'GET':
            form = UpdateReportForm(instance=report)
            return render(request, 'update_report.html', {'form': form, 'report': report})
        elif request.method == 'POST':
            form = UpdateReportForm(request.POST, instance=report)
            if form.is_valid():
                report.save()
                return redirect('my_reports')
            else:
                error = 'wrong data in form'
                return render(request, 'update_report.html', {'form': form, 'report': report, 'error': error})
        else:
            return render(request, "405.html", status=405)
    else:
        return render(request, "403.html", status=403)

citizen_report/report/templates/405.html
{% extends 'base.html' %}

{% block title %}
Error!
{% endblock title %}

{% block content %}

<h2>Method not allowed!</h2>

{% endblock content %}

citizen_report/report/templates/detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
{{report.title}}
{% endblock title %}

{% block content %}

<div class="container-fluid">
    <div class="col-10 mx-auto">
        <div class="p-3 m-3 mb-2 bg-white text-dark rounded border border-dark">
            <div class="row m-2">
                <h1 class="display-3 text-uppercase font-weight-bold">{{report.get_status_display}}</h1>
            </div>
            <div class="media">
                <div class="col-md-3 mx-auto">
                    <div class="row mx-auto">
                        <div class="col-sm-4">
                            <img src="{% static 'report/report-problem-icon3.jpg' %}" class="img-fluid">
                        </div>
                        <div class="col-sm-4">
                            <img src="{% static 'report/report-problem-icon3.jpg' %}" class="img-fluid">
                        </div>
                        <div class="col-sm-4">
                            <img src="{% static 'report/report-problem-icon3.jpg' %}" class="img-fluid">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row m-4">
                <div class="col-sm-6">
                    <h1 class="text-start">
                        <p class="text-uppercase font-weight-bold font-italic">{{report.title}}</p>
                    </h1>
                    <h3 class="text-start">
                        <p class="font-weight-bold font-italic">Category - {{report.get_category_display}}</p>
                    </h3>
                    <p class="text-start">Submitted by: {{report.user.username}}</p>
                    <p class="text-start"><small class="text-muted">Update date: {{report.updated_at}} | Submission date: {{report.created_at}}</small></p>
                    <hr class="my-2">
                </div>
                <div class="col-sm-6">
                    {% if report.image %}}
                    <img src="{{report.image.url}}" class="rounded mx-auto d-block"  alt="Report image">
                    {% endif %}
                </div>
            </div>
            <div class="row m-4">
                <div class="col-md-10 mx-auto">
                    <p class="font-italic">{{report.text}}</p>
                </div>
            </div>
            <div class="row">
                <hr class="my-2">
            </div>
            <div class="row m-4">
                <div class="col-md-12 d-flex justify-content-end">
                    <p class="card-text">Responsible Person: {{report.clerk.username}}</p>
                </div>
            </div>

            <div class="media">
                <div class="col-md-3 mx-auto">
                    <div class="row mx-auto">
                        <div class="col-sm-4">
                            <img src="{% static 'report/report-problem-icon3.jpg' %}" class="img-fluid">
                        </div>
                        <div class="col-sm-4">
                            <img src="{% static 'report/report-problem-icon3.jpg' %}" class="img-fluid">
                        </div>
                        <div class="col-sm-4">
                            <img src="{% static 'report/report-problem-icon3.jpg' %}" class="img-fluid">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="fixed-bottom p-3">
    <div class="row">
        <div class="col-sm-1">
            <a href="{{request.META.HTTP_REFERER|escape}}" class="btn btn-secondary">Back</a>
        </div>
        <div class="col-sm-11 d-flex justify-content-end">
        {% if posts %}
                <a href="{% url 'news' report.id %}" class="btn btn-dark">Check news</a>

        {% else %}
                <div class="badge badge-danger text-wrap" >
                    <h5 class="text-uppercase font-weight-bold align-center">No news yet!</h5>
                </div>
        {% endif %}
        </div>
    </div>
</div>


{% endblock content %}

citizen_report/report/templates/home.html
{% extends 'base.html' %}

{% block title %}
HOME
{% endblock title %}

{% block content %}

<h3>Home page.</h3>

{% endblock content %}

citizen_report/report/templates/my_reports.html
{% extends 'base.html' %}

{% block title %}
My reports
{% endblock title %}

{% block content %}

<div class="container">
    <div class="p-3 my-3 mb-2 bg-white text-dark rounded border border-dark" style="height: 760px">
        <div class="row justify-content-center">
                <div class="col-sm-6 my-4">
                    <h2 class="text-center">
                        {% if user.is_staff %}
                        <p class="text-uppercase font-weight-bold font-italic">My reports to evaluate:</p>
                        {% else %}
                        <p class="text-uppercase font-weight-bold font-italic">My reports:</p>
                        {% endif %}
                    </h2>
                </div>
                <div class="col-sm-6 my-4">
                    <form method="get">
                        <div class="form-group row">
                            <div class="col-sm-7 mr-sm-2">
                                <select id="inputStatus" class="form-control" name="status">
                                    {% for value,text in filter.form.status.field.choices  %}
                                    <option value="{{ value }}">{{ text }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            {% csrf_token %}
                            <button type="submit" class="btn btn-dark">Filter</button>
                        </div>
                    </form>
                </div>
        </div>
        <div class="container">
            {% if reports %}
                <div class="text-center">
                    {% for report in reports %}
                        {% if user.is_staff %}
                            <div class="col-md-6 mx-auto">
                                <div class="card my-4">
                                    <h3 class="card-header">Status: {{report.get_status_display}}</h3>
                                    <div class="card-body">
                                        <h2 class="card-title">{{report.title}}</h2>
                                        <p class="card-text"><small class="text-muted">Update date: {{report.updated_at}}</small></p>
                                        <p class="card-text"><small class="text-muted">Submission date: {{report.created_at}}</small></p>
                                        <a href="{% url 'update_report' report.id %}" class="btn btn-primary">Update status</a>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="col-md-6 mx-auto">
                                <div class="card my-4">
                                    <h3 class="card-header">Status: {{report.get_status_display}}</h3>
                                    <div class="card-body">
                                        <h2 class="card-title">{{report.title}}</h2>
                                        <p class="card-text"><small class="text-muted">Updated: {{report.updated_at}}</small></p>
                                        <p class="card-text"><small class="text-muted">Submited: {{report.created_at}}</small></p>
                                        <a href="{% url 'detail' report.id %}" class="btn btn-primary">Check report</a>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% else %}
                <div class="row justify-content-center">
                    <div class="badge badge-danger text-wrap" >
                        {% if user.is_staff %}
                            <h2 class="text-uppercase font-weight-bold align-center">No reports to evaluate</h2>
                        {% else %}
                            <h2 class="text-uppercase font-weight-bold align-center">No reports yet!</h2>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>


<div class="fixed-bottom d-flex p-3 justify-content-center">
    <nav aria-label="...">
        {% with request.get_full_path as querystring %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                {% if 'status' in querystring %}
                    {% if 'page' in querystring %}
                        <li class="page-item">
                            <a class="page-link" href="{{ querystring|slice:":-7" }}&page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{{ querystring }}&page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                        </li>
                    {% endif %}
                {% else %}
                    <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
            {% endif %}
            {% for page in page_obj.paginator.page_range %}
                {% if 'status' in querystring %}
                    {% if 'page' in querystring %}
                        <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                            <a class="page-link" href="{{ querystring|slice:":-7" }}&page={{ page }}">{{ page }}</a>
                        </li>
                    {% else %}
                        <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                            <a class="page-link" href="{{ querystring }}&page={{ page }}">{{ page }}</a>
                        </li>
                    {% endif %}
                {% else %}
                    <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                        <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                {% if 'status' in querystring %}
                    {% if 'page' in querystring %}
                        <li class="page-item">
                            <a class="page-link" href="{{ querystring|slice:":-7" }}&page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{{ querystring }}&page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                    {% endif %}
                {% else %}
                    <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next</a>
                </li>
            {% endif %}
        </ul>
        {% endwith %}
    </nav>
</div>

{% endblock content %}

citizen_report/report/templates/reports.html
{% extends 'base.html' %}

{% block title %}
Reports
{% endblock title %}

{% block content %}

<div class="container">
    <form method="GET" action="{% url 'reports' %}">
        <div class="form-group row my-3">
            <div class="col-sm-11 mr-sm-2">
                <input class="form-control" type="search" placeholder="Search" name="search">
            </div>
            <button class="btn btn-outline-secondary" type="submit" value="Search">Search</button>
        </div>
    </form>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-2 my-4">
            <div class="p-3 my-4 mb-2 bg-white text-dark rounded border border-dark">
                <h1 class="text-center">
                    <p class="text-uppercase font-weight-bold font-italic">Filter</p>
                </h1>
                <hr class="my-4">
                <form method="get">
                    <div class="form-group my-4 mr-sm-2">
                        <label class="my-2" for="inputCategory">Category</label>
                        <select id="inputCategory" class="form-control my-2" name="category">
                            {% for value,text in filter.form.category.field.choices  %}
                            <option value="{{ value }}">{{ text }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group my-4 mr-sm-2">
                        <label class="my-2" for="inputStatus">Status</label>
                        <select id="inputStatus" class="form-control my-2" name="status">
                            {% for value,text in filter.form.status.field.choices  %}
                            <option value="{{ value }}">{{ text }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    {% csrf_token %}
                    <div class="form-group my-4 mr-sm-2">
                        <div class="text-right">
                            <button type="submit" class="btn btn-dark">Filter</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
            {% if reports %}
                <div class="col-sm-8">
                    <div class="row">
                        {% for report in reports %}
                                <div class="col-sm-6">
                                    <div class="card my-4 bg-dark text-white">
                                        <h5 class="card-header">Status: {{report.get_status_display}}</h5>
                                        <div class="card-body">
                                            <h3 class="card-title">{{report.title}}</h3>
                                            <p class="card-text">Category: {{report.get_category_display}}</p>
                                            <a href="{% url 'detail' report.id %}" class="btn btn-primary">Check report</a>
                                        </div>
                                        <div class="card-footer text-muted">
                                            <p class="card-text">{{report.updated_at}}</p>
                                        </div>
                                    </div>
                                </div>
                        {% endfor %}
                    </div>
                </div>
            {% else %}
                <div class="col-sm-8 align-self-center">
                    <div class="row justify-content-center">
                        <div class="badge badge-danger text-wrap" >
                            <h1 class="text-uppercase font-weight-bold align-center">0 result found</h1>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>


<div class="fixed-bottom d-flex p-3 justify-content-center">
    <nav aria-label="...">
        {% with request.get_full_path as querystring %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                {% if 'category' in querystring %}
                    {% if 'page' in querystring %}
                        <li class="page-item">
                            <a class="page-link" href="{{ querystring|slice:":-7" }}&page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{{ querystring }}&page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                        </li>
                    {% endif %}
                {% elif 'search' in querystring %}
                    {% if 'page' in querystring %}
                        <li class="page-item">
                            <a class="page-link" href="{{ querystring|slice:":-7" }}&page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{{ querystring }}&page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                        </li>
                    {% endif %}
                {% else %}
                    <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
            {% endif %}
            {% for page in page_obj.paginator.page_range %}
                {% if 'category' in querystring %}
                    {% if 'page' in querystring %}
                        <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                            <a class="page-link" href="{{ querystring|slice:":-7" }}&page={{ page }}">{{ page }}</a>
                        </li>
                    {% else %}
                        <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                            <a class="page-link" href="{{ querystring }}&page={{ page }}">{{ page }}</a>
                        </li>
                    {% endif %}
                {% elif 'search' in querystring %}
                    {% if 'page' in querystring %}
                        <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                            <a class="page-link" href="{{ querystring|slice:":-7" }}&page={{ page }}">{{ page }}</a>
                        </li>
                    {% else %}
                        <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                            <a class="page-link" href="{{ querystring }}&page={{ page }}">{{ page }}</a>
                        </li>
                    {% endif %}
                {% else %}
                    <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                        <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                {% if 'category' in querystring %}
                    {% if 'page' in querystring %}
                        <li class="page-item">
                            <a class="page-link" href="{{ querystring|slice:":-7" }}&page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{{ querystring }}&page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                    {% endif %}
                {% elif 'search' in querystring %}
                    {% if 'page' in querystring %}
                        <li class="page-item">
                            <a class="page-link" href="{{ querystring|slice:":-7" }}&page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{{ querystring }}&page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                    {% endif %}
                {% else %}
                    <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next</a>
                </li>
            {% endif %}
        </ul>
        {% endwith %}
    </nav>
</div>

{% endblock content %}

citizen_report/report/templates/update_report.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Strona ze szczegółami
{% endblock title %}

{% block content %}

<div class="container">
    <div class="p-3 my-3 mb-2 bg-white text-dark rounded border border-dark" style="height: 760px">
        <div class="media">
            <div class="col-md-2 mx-auto">
                <img src="{% static 'report/report-problem-icon3.jpg' %}" class="img-fluid">
            </div>
        </div>
        <div class="row m-4">
            <div class="col-sm-6">
                <h1 class="text-start">
                    <p class="text-uppercase font-weight-bold font-italic">{{report.title}}</p>
                </h1>
                <h3 class="text-start">
                    <p class="font-weight-bold font-italic">Category - {{report.get_category_display}}</p>
                </h3>
                <p class="text-start">Submitted by: {{report.user.username}}</p>
                <p class="text-start"><small class="text-muted">Update date: {{report.updated_at}} | Submission date: {{report.created_at}}</small></p>
            </div>
            <div class="col-sm-6">
                {% if report.image %}}
                    <img src="{{report.image.url}}" class="rounded mx-auto d-block"  alt="Report image">
                {% endif %}
            </div>
        </div>
        <div class="row m-4">
            <div class="col-md-10 mx-auto">
                <p class="font-italic">{{report.text}}</p>
            </div>
        </div>
        <form method="post">
            <div class="col-md-8 mx-auto">
                <div class="form-group row m-4">
                    <label for="inputStatus" class="col-sm-2 col-form-label">Status:</label>
                    <div class="col-sm-9">
                        <select id="inputStatus" class="form-control" name="status" required>
                            <option value="{{report.status}}">{{ report.get_status_display }}</option>
                            {% for value,text in form.status.field.choices  %}
                                {% if report.status not in value %}
                                    <option value="{{ value }}">{{ text }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            {% csrf_token %}
            <div class="form-group row m-2">
                <div class="col-sm-12 text-right">
                    <button type="submit" class="btn btn-success">Change status</button>
                </div>
            </div>
        </form>
        <div class="form-group row m-2">
            <div class="col-sm-2 text-middle">
                <a href="{% url 'create_news' report.id %}" class="btn btn-dark">Create news</a>
            </div>
        </div>
        <div class="media">
            <div class="col-md-2 mx-auto">
                <img src="{% static 'report/report-problem-icon3.jpg' %}" class="img-fluid">
            </div>
        </div>
    </div>
</div>

<div class=" fixed-bottom p-3">
    <div class="form-group">
        <a href="{{request.META.HTTP_REFERER|escape}}" class="btn btn-secondary">Back</a>
    </div>
</div>


{% endblock content %}