citizen_report/citizen_report/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authSystem/', include('authSystem.urls')),
    path('', include('report.urls')),
    path('', include('news.urls')),
]

citizen_report/news/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path, include

from . import views

urlpatterns = [
    path('reports/<int:pk>/news/', views.NewsPostList.as_view(), name='news'),
    path('reports/<int:pk>/create-news/', staff_member_required(views.NewsPostCreate.as_view()), name='create_news'),
    path('news/<int:pk>/', views.NewsPostDetail.as_view(), name='detail_news'),
    path('news/<int:pk>/comment/', views.NewsCommentCreate.as_view(), name='add_comment_to_news'),
]

citizen_report/notifications/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('notifications/<int:pk>/detail', views.NotificationDetailView.as_view(), name='notification_detail'),
    path('notifications/', views.NotificationListView.as_view(), name='notifications_list'),
]

citizen_report/notifications/models.py
from django.db import models
from django.conf import settings

from report.models import Report

User = settings.AUTH_USER_MODEL


class Notification(models.Model):
    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    sent_at = models.DateTimeField(auto_now_add=True)
    message = models.CharField(max_length=200)
    is_read = models.BooleanField(default=False)

    class Meta:
        ordering = ['-sent_at']

    def __str__(self):
        return self.message

    def __repr__(self):
        return f'{self.report}, {self.user}, {self.sent_at}, {self.message}, {self.is_read}'

citizen_report/notifications/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, ListView

from .models import Notification


class NotificationDetailView(LoginRequiredMixin, DetailView):
    model = Notification
    template_name = 'notification_detail.html'

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        Notification.objects.filter(pk=self.kwargs['pk']).update(is_read=True)
        return queryset.filter(id=self.kwargs['pk'])


class NotificationListView(LoginRequiredMixin, ListView):
    model = Notification
    paginate_by = 5
    template_name = 'my_notifications.html'

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        return queryset.filter(user=self.request.user)

citizen_report/notifications/templates/my_notifications.html
{% extends 'base.html' %}

{% block title %}
	My notifications
{% endblock title %}

{% block content %}

<div class="container">
    {% if notification_list %}
        {% for notification in notification_list %}
            {% if notification.is_read %}
                <div class="card mb-3 my-4">
                    <div class="card-body">
                        <a class="card-link text-info" href="{% url 'notification_detail' notification.id %}">
                            <h5 class="card-title text-uppercase">
                                {{notification.report.title}}
                            </h5>
                            <p class="card-text"><small class="text-muted">Last updated: {{ notification.sent_at }}</small></p>
                        </a>
                    </div>
                </div>
            {% else %}
                <div class="card border-dark  mb-3 my-4">
                    <div class="card-body">
                        <a class="card-link text-info" href="{% url 'notification_detail' notification.id %}">
                            <h5 class="card-title text-uppercase font-weight-bold">
                                {{notification.report.title}} <span class="badge badge-secondary">New</span>
                            </h5>
                            <p class="card-text"><small class="text-muted">Last updated: {{ notification.sent_at }}</small></p>
                        </a>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% else %}
    <div class="col my-4">
        <div class="col-sm-12 align-self-center">
            <div class="row justify-content-center">
                <div class="badge badge-danger text-wrap" >
                    <h1 class="text-uppercase font-weight-bold align-center">0 notification for you</h1>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>

<div class="fixed-bottom d-flex p-3 justify-content-center">
    <nav aria-label="...">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
            </li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
            {% endif %}
            <li class="page-item active">
                <a class="page-link" href="#">{{ page_obj.number }} <span class="sr-only">(current)</span></a>
            </li>
            {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>

{% endblock content%}

citizen_report/notifications/templates/notification_detail.html
{% extends 'base.html' %}


{% block title %}
	{{ notification.report }}
{% endblock %}

{% block content %}

<div class="container">
    <div class="p-3 my-3 mb-2 bg-white text-dark rounded border border-dark">
        <div class="row m-4">
            <h1 class="text-uppercase font-weight-bold">{{notification.report.title}}</h1>
        </div>
        <div class="row m-4">
            <div class="col-sm-6">
                <p class="text-start"> {{notification.sent_at}}</p>
            </div>
        </div>
        <div class="row m-4">
            <div class="col-md-10 mx-auto">
                <p class="font-italic">{{notification.message|safe  }}</p>
            </div>
        </div>
        <div class="row">
            <hr class="my-2">
        </div>
        <div class="row m-2">
            {% if notification.report %}
            <div class="col-md-12 d-flex justify-content-end">
                <a class="btn btn-info btn-lg" href="{% url 'detail' notification.report.id %}" role="button">Check it out!</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>

<div class=" fixed-bottom p-3">
    <div class="row">
        <div class="col-sm-1">
            <a href="{{request.META.HTTP_REFERER|escape}}" class="btn btn-secondary">Back</a>
        </div>
    </div>
</div>

{% endblock %}