citizen_report/citizen_report/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authSystem/', include('authSystem.urls')),
    path('', include('report.urls')),
    path('', include('news.urls')),
]

citizen_report/news/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path, include

from . import views

urlpatterns = [
    path('reports/<int:pk>/news/', views.NewsPostList.as_view(), name='news'),
    path('reports/<int:pk>/create-news/', staff_member_required(views.NewsPostCreate.as_view()), name='create_news'),
    path('news/<int:pk>/', views.NewsPostDetail.as_view(), name='detail_news'),
    path('news/<int:pk>/comment/', views.NewsCommentCreate.as_view(), name='add_comment_to_news'),
]

citizen_report/news/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.conf import settings

from report.models import Report

User = settings.AUTH_USER_MODEL


class NewsPost(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images/', blank=True)
    clerk = models.ForeignKey(User, on_delete=models.CASCADE, related_name='news_posts', limit_choices_to={"is_staff": True})
    report = models.ForeignKey(Report, on_delete=models.CASCADE, related_name='report_posts')

    class Meta:
        ordering = ['-created_at']

    def __str__(self) -> str:
        return f'{self.title} | {self.created_at}'


class NewsComment(models.Model):
    post = models.ForeignKey(NewsPost, on_delete=models.CASCADE,related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    approved_comment = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return 'Comment {} by {}'.format(self.text, self.user)

citizen_report/news/forms.py
from django import forms

from .models import NewsPost, NewsComment


class NewsForm(forms.ModelForm):
    class Meta:
        model = NewsPost
        fields = ('title', 'text', 'image')


class NewsCommentForm(forms.ModelForm):

    class Meta:
        model = NewsComment
        fields = ('text',)

citizen_report/news/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic

from .forms import NewsForm, NewsCommentForm
from .models import NewsPost
from report.models import Report


class NewsPostList(generic.ListView):
    model = NewsPost
    template_name = 'news.html'
    paginate_by = 2

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        return queryset.filter(report_id=self.kwargs['pk'])


class NewsPostDetail(generic.DetailView):
    model = NewsPost
    template_name = 'detail_news.html'


class NewsPostCreate(LoginRequiredMixin, generic.CreateView):
    login_url = 'login'
    form_class = NewsForm
    success_url = reverse_lazy("my_reports")
    template_name = "create_news.html"

    def form_valid(self, form):
        form.instance.report = get_object_or_404(Report, pk=self.kwargs['pk'])
        form.instance.clerk = self.request.user
        return super(NewsPostCreate, self).form_valid(form)


class NewsCommentCreate(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    login_url = 'login'
    form_class = NewsCommentForm
    template_name = "add_comment_to_news.html"
    success_message = "Your comment is being moderated."

    def form_valid(self, form):
        form.instance.post = get_object_or_404(NewsPost, pk=self.kwargs['pk'])
        form.instance.user = self.request.user
        return super(NewsCommentCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('detail_news', kwargs={'pk': self.kwargs.get('pk')})

citizen_report/news/templates/add_comment_to_news.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Add comment{% endblock %}


{% block content %}

<div class="p-3 mb-4 container">
    <div class="p-3 mb-4 bg-white text-dark rounded border border-dark col-sm-8 mx-auto">
        <h3 class="text-center">
            <p class="text-uppercase font-weight-bold font-italic">New comment</p>
        </h3>
        <form method="post">
            <div class="form-group ">
                <textarea class="form-control" id="textarea" rows="6" name="text" placeholder="Write your comment" required></textarea>
            </div>
            {% csrf_token %}
            <div class="form-group row">
                <div class="col-sm-12 text-right">
                    <button type="submit" class="btn btn-primary">Send comment</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="fixed-bottom d-flex p-3">
    <div class="form-group">
        <a href="{{request.META.HTTP_REFERER|escape}}" class="btn btn-secondary">Back</a>
    </div>
</div>


{% endblock %}

citizen_report/news/templates/add_comment_to_post.html
{% extends 'base.html' %}

{% block content %}
<h1>New comment</h1>
<form method="POST" >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send</button>
</form>
{% endblock %}

citizen_report/news/templates/create_news.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Create news{% endblock %}

{% block content %}

<div class="container p-3">
    <div class="p-4 mb-2 bg-white text-dark rounded border border-dark">
        <h1 class="text-center">
            <p class="text-uppercase font-weight-bold font-italic">new post</p>
        </h1>
        <div class="media">
            <div class="col-md-2 mx-auto">
                <img src="{% static 'news/news-problem-icon3.jpg' %}" class="img-fluid">
            </div>
        </div>
        <form method="post">
            <div class="form-group row m-2">
                <label for="inputTitle" class="col-sm-2 col-form-label">Title</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="inputTitle" placeholder="Title" name="title" required>
                </div>
            </div>
            <div class="form-group m-4">
                <label for="textarea">Text</label>
                <textarea class="form-control" id="textarea" rows="7" name="text" placeholder="Describe evaluation to your report" required></textarea>
            </div>
            <div class="form-group m-4">
                <div class="custom-file">
                    <input type="file" class="custom-file-input" id="validatedCustomFile" name="image">
                    <label class="custom-file-label" for="validatedCustomFile">Attach file...</label>
                </div>
            </div>
            {% csrf_token %}
            <div class="form-group row m-2">
                <div class="col-sm-12 text-right">
                    <button type="submit" class="btn btn-success">Send post</button>
                </div>
            </div>
            <div class="container">
                <div class="col-md-2 mx-auto">
                    <img src="{% static 'news/news-problem-icon3.jpg' %}" class="img-fluid">
                </div>
            </div>
        </form>
    </div>
</div>

<div class="fixed-bottom d-flex p-3">
    <div class="form-group">
        <a href="{{request.META.HTTP_REFERER|escape}}" class="btn btn-secondary">Back</a>
    </div>
</div>

{% endblock %}

citizen_report/news/templates/create_post.html
{% extends 'base.html' %}

{% block title %}Create post{% endblock %}

{% block content %}
<h2>Create post</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create post</button>
</form>
{% endblock %}

citizen_report/news/templates/detail_news.html
{% extends 'base.html' %}


{%block title%}
{{newspost.title}}
{% endblock title%}

{% block content %}

{% if messages %}
<div class="p-3 container-fluid ">
    {% for message in messages %}
    <div class="alert alert-info" role="alert">
        {{message}}
    </div>
    {% endfor %}
</div>
{% endif %}

<div class="container-fluid">
    <div class="p-3 my-3 mb-2 bg-white text-dark rounded border border-dark">
        <div class="row m-4">
            <h1 class="display-4 text-uppercase font-weight-bold">{{newspost.title}}</h1>
        </div>
        <div class="row m-4">
            <div class="col-sm-6">
                <p class="text-start"> {{newspost.clerk.username}} | {{newspost.created_at}}</p>
            </div>
        </div>
        <div class="row m-4">
            <div class="col-sm-6 mx-auto">
                {% if newspost.image %}
                    <img src="{{newspost.image.url}}" class="rounded mx-auto d-block"  alt="Report image">
                {% endif %}
            </div>
        </div>
        <div class="row m-4">
            <div class="col-md-10 mx-auto">
                <p class="font-italic">{{newspost.text|safe  }}</p>
            </div>
        </div>
        <div class="row">
            <hr class="my-2">
        </div>
        <div class="row m-2">
            {% if user.is_authenticated %}
                <div class="col-md-12 d-flex justify-content-end">
                    <a class="btn btn-primary btn-lg" href="{% url 'add_comment_to_news' newspost.id %}" role="button">Add comment</a>
                </div>
            {% else %}
                <div class="col-md-12 d-flex justify-content-end">
                    <div class="form-group">
                    <a class="text-info" href="{% url 'login' %}">Log in</a> to comment
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>

<hr class="my-3">

{% for comment in newspost.comments.all %}
    {% if comment.approved_comment %}
        <div class="container">
            <div class="p-3 my-3 mb-2 bg-light text-dark rounded border">
                <div class="row">
                    <div class="col-md-8">
                        <p class="text-start font-weight-bold m-0">{{ comment.user.username }}</p>
                        <p class="text-start m-0"> <small class="text-muted"> {{ comment.created_at }} </small></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-10 mx-auto">
                        <p class="font-italic">{{ comment.text|linebreaks }}</p>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% empty %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h3 class="text-start font-weight-bold m-1">No comments here yet</h3>
            <p class="text-start m-1"> Be the first to comment </p>
        </div>
    </div>
</div>
{% endfor %}

<div class=" fixed-bottom p-3">
    <div class="row">
        <div class="col-sm-1">
            <a href="{{request.META.HTTP_REFERER|escape}}" class="btn btn-secondary">Back</a>
        </div>
    </div>
</div>

{% endblock content %}

citizen_report/news/templates/news.html
{% extends 'base.html' %}

{% block title %}News{% endblock %}

{% block content %}

<div class="container p-2">
    {% for post in newspost_list %}
        <div class="jumbotron my-4 p-4">
            <h1 class="display-5">{{post.title}}</h1>
            <p class="font-italic"><small class="text-muted">{{post.created_at}}</small></p>
            <p class="lead">{{post.text|slice:":100" }}</p>
            <hr class="my-3">
            <p>Comments: {{ post.comments.count }}</p>
            <a class="btn btn-primary btn-lg" href="{% url 'detail_news' post.id %}" role="button">Read More</a>
        </div>
    {% endfor %}
</div>

<div class="fixed-bottom p-3">
    <div class="row">
        <div class="col-sm-1">
            <a href="{{request.META.HTTP_REFERER|escape}}" class="btn btn-secondary">Back</a>
        </div>
        <div class="col-sm-10 d-flex justify-content-center">
            <nav aria-label="...">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                    </li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#" tabindex="-1">Previous</a>
                    </li>
                    {% endif %}
                    <li class="page-item active">
                        <a class="page-link" href="">{{ page_obj.number }} <span class="sr-only">(current)</span></a>
                    </li>
                    {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</div>


{% endblock %}